version: '3.9'

services:
  db:
    container_name: db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stripe101
    ports:
      - "3307:3306"
    volumes:
      - stripe101_db:/var/lib/mysql
    
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8888:80"
    depends_on:
      - db

volumes:
  stripe101_db: